### ISSUE TITLE
サンプルコードでエラーが出た

### ISSUE THREAD

**Issue by 45deg** [45deg/rws-ruby-sdk#4]
```
~/sandbox/rakuten ⮀ ruby search_sample.rb
/Users/kazuhiro/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/client.rb:18:in `initialize': uninitialized constant RakutenWebService::Client::URI (NameError)
    from /Users/kazuhiro/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/search_result.rb:8:in `new'
    from /Users/kazuhiro/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/search_result.rb:8:in `initialize'
    from /Users/kazuhiro/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/resource.rb:29:in `new'
    from /Users/kazuhiro/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/resource.rb:29:in `search'
    from search_sample.rb:7:in `<main>'
```

ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

**Comment by 45deg** [comment]
サンプルコードで

```
require 'uri'
```

したら治った

`lib/rakuten_web_service/client.rb` に `require 'uri'` する
