### ISSUE TITLE
RakutenWebService::Books::Genre.search のテストを通す

### ISSUE THREAD

**Issue by 45deg** [45deg/rws-ruby-sdk#7]
```
  1) RakutenWebService::Books::Genre.search call the endpoint once
     Failure/Error: to_return(:body => expected_json)
     WebMock::Response::InvalidBody:
       must be one of: [Proc, IO, Pathname, String, Array]. 'Hash' given
     # ./spec/rakuten_web_service/books/genre_spec.rb:27:in `block (2 levels) in <top (required)>'

  2) RakutenWebService::Books::Genre.search has interfaces like hash
     Failure/Error: to_return(:body => expected_json)
     WebMock::Response::InvalidBody:
       must be one of: [Proc, IO, Pathname, String, Array]. 'Hash' given
     # ./spec/rakuten_web_service/books/genre_spec.rb:27:in `block (2 levels) in <top (required)>'

  3) RakutenWebService::Books::Genre.search has interfaces like hash with snake case key
     Failure/Error: to_return(:body => expected_json)
     WebMock::Response::InvalidBody:
       must be one of: [Proc, IO, Pathname, String, Array]. 'Hash' given
     # ./spec/rakuten_web_service/books/genre_spec.rb:27:in `block (2 levels) in <top (required)>'

  4) RakutenWebService::Books::Genre.search has interfaces to get each attribute
     Failure/Error: to_return(:body => expected_json)
     WebMock::Response::InvalidBody:
       must be one of: [Proc, IO, Pathname, String, Array]. 'Hash' given
     # ./spec/rakuten_web_service/books/genre_spec.rb:27:in `block (2 levels) in <top (required)>'
```

it fails

**Comment by 45deg** [comment]
spec/rakuten_web_service/books/game_spec.rb:27

``` ruby
with(:query => expected_query).to_return(:body => response.to_json)
```

で治ることは治った（謎）

追記：to_return の引数パラメータ :body は文字列である必要があるから to_json かまさないと死ぬ
というか begin で死んでたからそれ以下のテスト全部死んでた😭
