### ISSUE TITLE
RakutenWebService::Books::Genre.new のテストが通らない

### ISSUE THREAD

**Issue by 45deg** [45deg/rws-ruby-sdk#9]
``` ruby
  1) RakutenWebService::Books::Genre.new given a genre id only call endpint only at the first time to initialize
     Failure/Error: @genre = RWS::Books::Genre.new(param)
     Faraday::ParsingError:
       757: unexpected token at '"{\"current\":{\"booksGenreId\":\"007\",\"booksGenreName\":\"DummyGenre\",\"genreLevel\":\"2\"}}"'
     # ./lib/rakuten_web_service/client.rb:26:in `get'
     # ./lib/rakuten_web_service/search_result.rb:55:in `query'
     # ./lib/rakuten_web_service/search_result.rb:17:in `each'
     # ./lib/rakuten_web_service/genre.rb:25:in `first'
     # ./lib/rakuten_web_service/genre.rb:25:in `new'
     # ./spec/rakuten_web_service/books/genre_spec.rb:70:in `block (3 levels) in <top (required)>'
```

**Comment by 45deg** [comment]
spec/rakuten_web_service/books/genre_spec.rb:66 の `to_json` を消したら通った
